---
language: php

php:
    - '7.1'

notifications:
    email: false

before_install:
    - composer install
    - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.0/coveralls.phar
    - chmod +x coveralls.phar

before_script:
    - echo 'zend.assertions = 1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - echo 'assert.exception = 1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
    - php bin/task build

after_success:
    - travis_retry php coveralls.phar
